### ISSUE TITLE
Cannot flash - Invalid response length

### ISSUE THREAD

**Issue by kareltucek** [kareltucek/firmware#117]
When trying to flash my UHKv1 from commandline, I am getting:

```
Updating right firmware from build_make/uhk60v1.hex ...
Error: Invalid response length!
    at decodeCommandResponse (file:///opt/firmware/lib/agent/packages/kboot/src/util/usb/decode-command-response.ts:6:15)
    at file:///opt/firmware/lib/agent/packages/kboot/src/usb-peripheral.ts:67:41
    at new Promise (<anonymous>)
    at UsbPeripheral.sendCommand (file:///opt/firmware/lib/agent/packages/kboot/src/usb-peripheral.ts:58:16)
    at KBoot.reset (file:///opt/firmware/lib/agent/packages/kboot/src/kboot.ts:171:46)
    at UhkOperations.updateRightFirmwareWithKboot (file:///opt/firmware/lib/agent/packages/uhk-usb/src/uhk-operations.ts:96:21)
    at async file:///opt/firmware/lib/agent/packages/usb/update-device-firmware.ts:25:9
make: *** [../../scripts/Makedefs.mk:191: flash] Error 1
```

When trying to flash from Agent, I get a similar result (3.1.0).

When trying to unbrick the unit (via shorting the reset pins and then clicking fix device in Agent), I also the same result.

(This is with drift-detection testing firmware.)

Any ideas what might be wrong and/or how to fix it?

**Comment by kareltucek** [comment]
Ah, of course, usb hub in way... also created this in the wrong repo 🤦.
